services:
  # agent runtime process
  agent-runtime:
    image: hishtribes/agentcoin-runtime
    restart: always
    working_dir: /root/.agentcoin-fun/code
    command: ['bun', 'run', 'agent']
    networks:
      - skynet
    volumes:
      - ${HOME}/.agentcoin-fun:/root/.agentcoin-fun
    tmpfs:
      - /tmp:exec,mode=777
    depends_on:
      - agent-sentinel

  # agent sentinel process
  agent-sentinel:
    image: hishtribes/agentcoin-runtime
    restart: always
    working_dir: /root/sentinel
    command: ['bun', 'run', 'agent']
    networks:
      - skynet
    volumes:
      - ${HOME}/.agentcoin-fun:/root/.agentcoin-fun
    tmpfs:
      - /tmp:exec,mode=777

  # watchtower for automatic updates
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup agent-runtime agent-sentinel
    networks:
      - skynet

networks:
  skynet:
    driver: bridge
    internal: false
