services:
  # agent runtime process
  agent-runtime:
    image: hishtribes/agentcoin-runtime
    restart: always
    working_dir: /root/runtime
    command: ['bun', 'run', 'agent']
    # TODO: hish - add this back -> read_only: true
    networks:
      - skynet
    volumes:
      - ${HOME}/.agentcoin-fun:/root/.agentcoin-fun
    tmpfs:
      - /tmp:exec,mode=777
    depends_on:
      - agent-sentinel

  # agent sentinel process
  agent-sentinel:
    image: hishtribes/agentcoin-runtime
    restart: always
    working_dir: /root/sentinel
    command: ['bun', 'run', 'agent']
    networks:
      - skynet
    volumes:
      - ${HOME}/.agentcoin-fun:/root/.agentcoin-fun
    tmpfs:
      - /tmp:exec,mode=777

networks:
  skynet:
    driver: bridge
    internal: false
